### PR TITLE
Fix TODOs in marshalling

### LINKED ISSUE #73: Address TODOs in marshalling

### PR DESCRIPTION
**Pull request by vo-nil**
closes #73

### CODE REVIEW

File: crypto3/libs/algebra/include/nil/crypto3/algebra/curves/detail/forms/twisted_edwards/extended_with_a_minus_1/element_g1.hpp [hunk 1]
```diff
@@ -221,21 +221,18 @@ namespace nil {
 
                         /*************************  Arithmetic operations  ***********************************/
 
-                        constexpr curve_element operator=(const curve_element &other) {
-                            // handle special cases having to do with O
+                        constexpr curve_element& operator=(curve_element<params_type, form, curves::coordinates::affine> const &other) {
                             this->X = other.X;
                             this->Y = other.Y;
-                            this->T = other.T;
```
Comment (martun) [inline crypto3/libs/algebra/include/nil/crypto3/algebra/curves/detail/forms/twisted_edwards/extended_with_a_minus_1/element_g1.hpp:228]: Why do we need this change. At least add a comment, so the next person will read this easier.

**Review by martun — APPROVED** [review]

File: crypto3/libs/algebra/include/nil/crypto3/algebra/curves/detail/forms/twisted_edwards/extended_with_a_minus_1/element_g1.hpp (hunk 1 above)
Comment (vo-nil) [reply crypto3/libs/algebra/include/nil/crypto3/algebra/curves/detail/forms/twisted_edwards/extended_with_a_minus_1/element_g1.hpp:228]: Original `operator=` is removed, as it has trivial implementation. This is `operator=` from a different class - affine coordinates.
